// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum EnterGameResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EnterGameResponse<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EnterGameResponse<'a> {
  type Inner = EnterGameResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EnterGameResponse<'a> {
  pub const VT_CHARACTER: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EnterGameResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EnterGameResponseArgs<'args>
  ) -> flatbuffers::WIPOffset<EnterGameResponse<'bldr>> {
    let mut builder = EnterGameResponseBuilder::new(_fbb);
    if let Some(x) = args.character { builder.add_character(x); }
    builder.finish()
  }


  #[inline]
  pub fn character(&self) -> Option<Character<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Character>>(EnterGameResponse::VT_CHARACTER, None)}
  }
}

impl flatbuffers::Verifiable for EnterGameResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<Character>>("character", Self::VT_CHARACTER, false)?
     .finish();
    Ok(())
  }
}
pub struct EnterGameResponseArgs<'a> {
    pub character: Option<flatbuffers::WIPOffset<Character<'a>>>,
}
impl<'a> Default for EnterGameResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    EnterGameResponseArgs {
      character: None,
    }
  }
}

pub struct EnterGameResponseBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EnterGameResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_character(&mut self, character: flatbuffers::WIPOffset<Character<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Character>>(EnterGameResponse::VT_CHARACTER, character);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EnterGameResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EnterGameResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EnterGameResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EnterGameResponse<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EnterGameResponse");
      ds.field("character", &self.character());
      ds.finish()
  }
}
