// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum EnterGameRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EnterGameRequest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EnterGameRequest<'a> {
  type Inner = EnterGameRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EnterGameRequest<'a> {
  pub const VT_CHARACTER_ID: flatbuffers::VOffsetT = 4;
  pub const VT_TOKEN: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EnterGameRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EnterGameRequestArgs<'args>
  ) -> flatbuffers::WIPOffset<EnterGameRequest<'bldr>> {
    let mut builder = EnterGameRequestBuilder::new(_fbb);
    if let Some(x) = args.token { builder.add_token(x); }
    builder.add_character_id(args.character_id);
    builder.finish()
  }


  #[inline]
  pub fn character_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(EnterGameRequest::VT_CHARACTER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn token(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(EnterGameRequest::VT_TOKEN, None)}
  }
}

impl flatbuffers::Verifiable for EnterGameRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("character_id", Self::VT_CHARACTER_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("token", Self::VT_TOKEN, false)?
     .finish();
    Ok(())
  }
}
pub struct EnterGameRequestArgs<'a> {
    pub character_id: i32,
    pub token: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EnterGameRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    EnterGameRequestArgs {
      character_id: 0,
      token: None,
    }
  }
}

pub struct EnterGameRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EnterGameRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_character_id(&mut self, character_id: i32) {
    self.fbb_.push_slot::<i32>(EnterGameRequest::VT_CHARACTER_ID, character_id, 0);
  }
  #[inline]
  pub fn add_token(&mut self, token: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EnterGameRequest::VT_TOKEN, token);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EnterGameRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EnterGameRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EnterGameRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EnterGameRequest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EnterGameRequest");
      ds.field("character_id", &self.character_id());
      ds.field("token", &self.token());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `EnterGameRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_enter_game_request_unchecked`.
pub fn root_as_enter_game_request(buf: &[u8]) -> Result<EnterGameRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<EnterGameRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `EnterGameRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_enter_game_request_unchecked`.
pub fn size_prefixed_root_as_enter_game_request(buf: &[u8]) -> Result<EnterGameRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<EnterGameRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `EnterGameRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_enter_game_request_unchecked`.
pub fn root_as_enter_game_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EnterGameRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<EnterGameRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `EnterGameRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_enter_game_request_unchecked`.
pub fn size_prefixed_root_as_enter_game_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EnterGameRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<EnterGameRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a EnterGameRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `EnterGameRequest`.
pub unsafe fn root_as_enter_game_request_unchecked(buf: &[u8]) -> EnterGameRequest {
  flatbuffers::root_unchecked::<EnterGameRequest>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed EnterGameRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `EnterGameRequest`.
pub unsafe fn size_prefixed_root_as_enter_game_request_unchecked(buf: &[u8]) -> EnterGameRequest {
  flatbuffers::size_prefixed_root_unchecked::<EnterGameRequest>(buf)
}
#[inline]
pub fn finish_enter_game_request_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<EnterGameRequest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_enter_game_request_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<EnterGameRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
