// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod protocol {
  use super::*;
  mod token_user_data_generated;
  pub use self::token_user_data_generated::*;
} // protocol
