[package]
name = "netcode"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1.10.1"
chacha20poly1305 = "0.10.1"
octets = "0.3.0"
serde = "1.0.219"
serde-aux = "4.7.0"
tokio = { version = "1", features = ["full"] } 
tracing = "0.1.40"

