database:
  require_ssl: false
application:
  host: 127.0.0.1
  jwt_signing_key: secret
  # netcode_private_key: Z8ocDNthwK2cWI0XMIOVsEsKErlxSjuw7k0YibAucSk=
realm_resolver:
  type: local
  host: 127.0.0.1
  port: 8000
telemetry:
  tracing_format: pretty
  otel_exporter_endpoint: http://localhost:4317
