// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum BatchedActionsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BatchedActions<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for BatchedActions<'a> {
  type Inner = BatchedActions<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BatchedActions<'a> {
  pub const VT_ACTIONS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    BatchedActions { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BatchedActionsArgs<'args>
  ) -> flatbuffers::WIPOffset<BatchedActions<'bldr>> {
    let mut builder = BatchedActionsBuilder::new(_fbb);
    if let Some(x) = args.actions { builder.add_actions(x); }
    builder.finish()
  }


  #[inline]
  pub fn actions(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Action<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Action>>>>(BatchedActions::VT_ACTIONS, None)}
  }
}

impl flatbuffers::Verifiable for BatchedActions<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Action>>>>("actions", Self::VT_ACTIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct BatchedActionsArgs<'a> {
    pub actions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Action<'a>>>>>,
}
impl<'a> Default for BatchedActionsArgs<'a> {
  #[inline]
  fn default() -> Self {
    BatchedActionsArgs {
      actions: None,
    }
  }
}

pub struct BatchedActionsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> BatchedActionsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_actions(&mut self, actions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Action<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(BatchedActions::VT_ACTIONS, actions);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> BatchedActionsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BatchedActionsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<BatchedActions<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for BatchedActions<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("BatchedActions");
      ds.field("actions", &self.actions());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `BatchedActions`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_batched_actions_unchecked`.
pub fn root_as_batched_actions(buf: &[u8]) -> Result<BatchedActions, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<BatchedActions>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `BatchedActions` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_batched_actions_unchecked`.
pub fn size_prefixed_root_as_batched_actions(buf: &[u8]) -> Result<BatchedActions, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<BatchedActions>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `BatchedActions` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_batched_actions_unchecked`.
pub fn root_as_batched_actions_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BatchedActions<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<BatchedActions<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `BatchedActions` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_batched_actions_unchecked`.
pub fn size_prefixed_root_as_batched_actions_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BatchedActions<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<BatchedActions<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a BatchedActions and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `BatchedActions`.
pub unsafe fn root_as_batched_actions_unchecked(buf: &[u8]) -> BatchedActions {
  unsafe { flatbuffers::root_unchecked::<BatchedActions>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed BatchedActions and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `BatchedActions`.
pub unsafe fn size_prefixed_root_as_batched_actions_unchecked(buf: &[u8]) -> BatchedActions {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<BatchedActions>(buf) }
}
#[inline]
pub fn finish_batched_actions_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<BatchedActions<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_batched_actions_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<BatchedActions<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
