// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum EntityDeathEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EntityDeathEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EntityDeathEvent<'a> {
  type Inner = EntityDeathEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EntityDeathEvent<'a> {
  pub const VT_ENTITY_ID: flatbuffers::VOffsetT = 4;
  pub const VT_LOOT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EntityDeathEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntityDeathEventArgs<'args>
  ) -> flatbuffers::WIPOffset<EntityDeathEvent<'bldr>> {
    let mut builder = EntityDeathEventBuilder::new(_fbb);
    builder.add_entity_id(args.entity_id);
    if let Some(x) = args.loot { builder.add_loot(x); }
    builder.finish()
  }


  #[inline]
  pub fn entity_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(EntityDeathEvent::VT_ENTITY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn loot(&self) -> Option<flatbuffers::Vector<'a, ItemDrop>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, ItemDrop>>>(EntityDeathEvent::VT_LOOT, None)}
  }
}

impl flatbuffers::Verifiable for EntityDeathEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("entity_id", Self::VT_ENTITY_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, ItemDrop>>>("loot", Self::VT_LOOT, false)?
     .finish();
    Ok(())
  }
}
pub struct EntityDeathEventArgs<'a> {
    pub entity_id: u64,
    pub loot: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, ItemDrop>>>,
}
impl<'a> Default for EntityDeathEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntityDeathEventArgs {
      entity_id: 0,
      loot: None,
    }
  }
}

pub struct EntityDeathEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EntityDeathEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_entity_id(&mut self, entity_id: u64) {
    self.fbb_.push_slot::<u64>(EntityDeathEvent::VT_ENTITY_ID, entity_id, 0);
  }
  #[inline]
  pub fn add_loot(&mut self, loot: flatbuffers::WIPOffset<flatbuffers::Vector<'b , ItemDrop>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EntityDeathEvent::VT_LOOT, loot);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EntityDeathEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntityDeathEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EntityDeathEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EntityDeathEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EntityDeathEvent");
      ds.field("entity_id", &self.entity_id());
      ds.field("loot", &self.loot());
      ds.finish()
  }
}
