// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum EntitySpawnEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EntitySpawnEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EntitySpawnEvent<'a> {
  type Inner = EntitySpawnEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EntitySpawnEvent<'a> {
  pub const VT_ENTITY: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EntitySpawnEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntitySpawnEventArgs<'args>
  ) -> flatbuffers::WIPOffset<EntitySpawnEvent<'bldr>> {
    let mut builder = EntitySpawnEventBuilder::new(_fbb);
    if let Some(x) = args.entity { builder.add_entity(x); }
    builder.finish()
  }


  #[inline]
  pub fn entity(&self) -> Option<Entity<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Entity>>(EntitySpawnEvent::VT_ENTITY, None)}
  }
}

impl flatbuffers::Verifiable for EntitySpawnEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<Entity>>("entity", Self::VT_ENTITY, false)?
     .finish();
    Ok(())
  }
}
pub struct EntitySpawnEventArgs<'a> {
    pub entity: Option<flatbuffers::WIPOffset<Entity<'a>>>,
}
impl<'a> Default for EntitySpawnEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntitySpawnEventArgs {
      entity: None,
    }
  }
}

pub struct EntitySpawnEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EntitySpawnEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_entity(&mut self, entity: flatbuffers::WIPOffset<Entity<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Entity>>(EntitySpawnEvent::VT_ENTITY, entity);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EntitySpawnEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntitySpawnEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EntitySpawnEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EntitySpawnEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EntitySpawnEvent");
      ds.field("entity", &self.entity());
      ds.finish()
  }
}
