// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum NpcAttributesOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NpcAttributes<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NpcAttributes<'a> {
  type Inner = NpcAttributes<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NpcAttributes<'a> {
  pub const VT_ASSET_ID: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NpcAttributes { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NpcAttributesArgs
  ) -> flatbuffers::WIPOffset<NpcAttributes<'bldr>> {
    let mut builder = NpcAttributesBuilder::new(_fbb);
    builder.add_asset_id(args.asset_id);
    builder.finish()
  }


  #[inline]
  pub fn asset_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NpcAttributes::VT_ASSET_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for NpcAttributes<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("asset_id", Self::VT_ASSET_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct NpcAttributesArgs {
    pub asset_id: u32,
}
impl<'a> Default for NpcAttributesArgs {
  #[inline]
  fn default() -> Self {
    NpcAttributesArgs {
      asset_id: 0,
    }
  }
}

pub struct NpcAttributesBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NpcAttributesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_asset_id(&mut self, asset_id: u32) {
    self.fbb_.push_slot::<u32>(NpcAttributes::VT_ASSET_ID, asset_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NpcAttributesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NpcAttributesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NpcAttributes<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NpcAttributes<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NpcAttributes");
      ds.field("asset_id", &self.asset_id());
      ds.finish()
  }
}
