// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PlayerMoveActionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PlayerMoveAction<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PlayerMoveAction<'a> {
  type Inner = PlayerMoveAction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PlayerMoveAction<'a> {
  pub const VT_TRANSFORM: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PlayerMoveAction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PlayerMoveActionArgs<'args>
  ) -> flatbuffers::WIPOffset<PlayerMoveAction<'bldr>> {
    let mut builder = PlayerMoveActionBuilder::new(_fbb);
    if let Some(x) = args.transform { builder.add_transform(x); }
    builder.finish()
  }


  #[inline]
  pub fn transform(&self) -> Option<&'a Transform> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Transform>(PlayerMoveAction::VT_TRANSFORM, None)}
  }
}

impl flatbuffers::Verifiable for PlayerMoveAction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<Transform>("transform", Self::VT_TRANSFORM, false)?
     .finish();
    Ok(())
  }
}
pub struct PlayerMoveActionArgs<'a> {
    pub transform: Option<&'a Transform>,
}
impl<'a> Default for PlayerMoveActionArgs<'a> {
  #[inline]
  fn default() -> Self {
    PlayerMoveActionArgs {
      transform: None,
    }
  }
}

pub struct PlayerMoveActionBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PlayerMoveActionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_transform(&mut self, transform: &Transform) {
    self.fbb_.push_slot_always::<&Transform>(PlayerMoveAction::VT_TRANSFORM, transform);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerMoveActionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PlayerMoveActionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerMoveAction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerMoveAction<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerMoveAction");
      ds.field("transform", &self.transform());
      ds.finish()
  }
}
