// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PlayerAttributesOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PlayerAttributes<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PlayerAttributes<'a> {
  type Inner = PlayerAttributes<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PlayerAttributes<'a> {
  pub const VT_CHARACTER_ID: flatbuffers::VOffsetT = 4;
  pub const VT_GUILD_NAME: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PlayerAttributes { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PlayerAttributesArgs<'args>
  ) -> flatbuffers::WIPOffset<PlayerAttributes<'bldr>> {
    let mut builder = PlayerAttributesBuilder::new(_fbb);
    if let Some(x) = args.guild_name { builder.add_guild_name(x); }
    builder.add_character_id(args.character_id);
    builder.finish()
  }


  #[inline]
  pub fn character_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(PlayerAttributes::VT_CHARACTER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn guild_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PlayerAttributes::VT_GUILD_NAME, None)}
  }
}

impl flatbuffers::Verifiable for PlayerAttributes<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("character_id", Self::VT_CHARACTER_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("guild_name", Self::VT_GUILD_NAME, false)?
     .finish();
    Ok(())
  }
}
pub struct PlayerAttributesArgs<'a> {
    pub character_id: i32,
    pub guild_name: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PlayerAttributesArgs<'a> {
  #[inline]
  fn default() -> Self {
    PlayerAttributesArgs {
      character_id: 0,
      guild_name: None,
    }
  }
}

pub struct PlayerAttributesBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PlayerAttributesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_character_id(&mut self, character_id: i32) {
    self.fbb_.push_slot::<i32>(PlayerAttributes::VT_CHARACTER_ID, character_id, 0);
  }
  #[inline]
  pub fn add_guild_name(&mut self, guild_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PlayerAttributes::VT_GUILD_NAME, guild_name);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerAttributesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PlayerAttributesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerAttributes<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerAttributes<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerAttributes");
      ds.field("character_id", &self.character_id());
      ds.field("guild_name", &self.guild_name());
      ds.finish()
  }
}
