// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PongEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PongEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PongEvent<'a> {
  type Inner = PongEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PongEvent<'a> {
  pub const VT_SEQUENCE: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PongEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PongEventArgs
  ) -> flatbuffers::WIPOffset<PongEvent<'bldr>> {
    let mut builder = PongEventBuilder::new(_fbb);
    builder.add_sequence(args.sequence);
    builder.finish()
  }


  #[inline]
  pub fn sequence(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(PongEvent::VT_SEQUENCE, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for PongEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("sequence", Self::VT_SEQUENCE, false)?
     .finish();
    Ok(())
  }
}
pub struct PongEventArgs {
    pub sequence: u32,
}
impl<'a> Default for PongEventArgs {
  #[inline]
  fn default() -> Self {
    PongEventArgs {
      sequence: 0,
    }
  }
}

pub struct PongEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PongEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sequence(&mut self, sequence: u32) {
    self.fbb_.push_slot::<u32>(PongEvent::VT_SEQUENCE, sequence, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PongEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PongEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PongEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PongEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PongEvent");
      ds.field("sequence", &self.sequence());
      ds.finish()
  }
}
