// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RttReportActionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RttReportAction<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RttReportAction<'a> {
  type Inner = RttReportAction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RttReportAction<'a> {
  pub const VT_PING_SEQUENCE: flatbuffers::VOffsetT = 4;
  pub const VT_RTT_MS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RttReportAction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RttReportActionArgs
  ) -> flatbuffers::WIPOffset<RttReportAction<'bldr>> {
    let mut builder = RttReportActionBuilder::new(_fbb);
    builder.add_rtt_ms(args.rtt_ms);
    builder.add_ping_sequence(args.ping_sequence);
    builder.finish()
  }


  #[inline]
  pub fn ping_sequence(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(RttReportAction::VT_PING_SEQUENCE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn rtt_ms(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(RttReportAction::VT_RTT_MS, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RttReportAction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("ping_sequence", Self::VT_PING_SEQUENCE, false)?
     .visit_field::<f32>("rtt_ms", Self::VT_RTT_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct RttReportActionArgs {
    pub ping_sequence: u32,
    pub rtt_ms: f32,
}
impl<'a> Default for RttReportActionArgs {
  #[inline]
  fn default() -> Self {
    RttReportActionArgs {
      ping_sequence: 0,
      rtt_ms: 0.0,
    }
  }
}

pub struct RttReportActionBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RttReportActionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ping_sequence(&mut self, ping_sequence: u32) {
    self.fbb_.push_slot::<u32>(RttReportAction::VT_PING_SEQUENCE, ping_sequence, 0);
  }
  #[inline]
  pub fn add_rtt_ms(&mut self, rtt_ms: f32) {
    self.fbb_.push_slot::<f32>(RttReportAction::VT_RTT_MS, rtt_ms, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RttReportActionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RttReportActionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RttReportAction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RttReportAction<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RttReportAction");
      ds.field("ping_sequence", &self.ping_sequence());
      ds.field("rtt_ms", &self.rtt_ms());
      ds.finish()
  }
}
