// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum SpellImpactEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SpellImpactEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SpellImpactEvent<'a> {
  type Inner = SpellImpactEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SpellImpactEvent<'a> {
  pub const VT_TARGET_ID: flatbuffers::VOffsetT = 4;
  pub const VT_SPELL_ID: flatbuffers::VOffsetT = 6;
  pub const VT_IMPACT_AMOUNT: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SpellImpactEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SpellImpactEventArgs
  ) -> flatbuffers::WIPOffset<SpellImpactEvent<'bldr>> {
    let mut builder = SpellImpactEventBuilder::new(_fbb);
    builder.add_target_id(args.target_id);
    builder.add_impact_amount(args.impact_amount);
    builder.add_spell_id(args.spell_id);
    builder.finish()
  }


  #[inline]
  pub fn target_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SpellImpactEvent::VT_TARGET_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn spell_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SpellImpactEvent::VT_SPELL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn impact_amount(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(SpellImpactEvent::VT_IMPACT_AMOUNT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for SpellImpactEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("target_id", Self::VT_TARGET_ID, false)?
     .visit_field::<u32>("spell_id", Self::VT_SPELL_ID, false)?
     .visit_field::<i32>("impact_amount", Self::VT_IMPACT_AMOUNT, false)?
     .finish();
    Ok(())
  }
}
pub struct SpellImpactEventArgs {
    pub target_id: u64,
    pub spell_id: u32,
    pub impact_amount: i32,
}
impl<'a> Default for SpellImpactEventArgs {
  #[inline]
  fn default() -> Self {
    SpellImpactEventArgs {
      target_id: 0,
      spell_id: 0,
      impact_amount: 0,
    }
  }
}

pub struct SpellImpactEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SpellImpactEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_target_id(&mut self, target_id: u64) {
    self.fbb_.push_slot::<u64>(SpellImpactEvent::VT_TARGET_ID, target_id, 0);
  }
  #[inline]
  pub fn add_spell_id(&mut self, spell_id: u32) {
    self.fbb_.push_slot::<u32>(SpellImpactEvent::VT_SPELL_ID, spell_id, 0);
  }
  #[inline]
  pub fn add_impact_amount(&mut self, impact_amount: i32) {
    self.fbb_.push_slot::<i32>(SpellImpactEvent::VT_IMPACT_AMOUNT, impact_amount, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SpellImpactEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SpellImpactEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SpellImpactEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SpellImpactEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SpellImpactEvent");
      ds.field("target_id", &self.target_id());
      ds.field("spell_id", &self.spell_id());
      ds.field("impact_amount", &self.impact_amount());
      ds.finish()
  }
}
