// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum StartCastingEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StartCastingEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for StartCastingEvent<'a> {
  type Inner = StartCastingEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> StartCastingEvent<'a> {
  pub const VT_ENTITY_ID: flatbuffers::VOffsetT = 4;
  pub const VT_SPELL_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    StartCastingEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StartCastingEventArgs
  ) -> flatbuffers::WIPOffset<StartCastingEvent<'bldr>> {
    let mut builder = StartCastingEventBuilder::new(_fbb);
    builder.add_entity_id(args.entity_id);
    builder.add_spell_id(args.spell_id);
    builder.finish()
  }


  #[inline]
  pub fn entity_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(StartCastingEvent::VT_ENTITY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn spell_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(StartCastingEvent::VT_SPELL_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for StartCastingEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("entity_id", Self::VT_ENTITY_ID, false)?
     .visit_field::<u32>("spell_id", Self::VT_SPELL_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct StartCastingEventArgs {
    pub entity_id: u64,
    pub spell_id: u32,
}
impl<'a> Default for StartCastingEventArgs {
  #[inline]
  fn default() -> Self {
    StartCastingEventArgs {
      entity_id: 0,
      spell_id: 0,
    }
  }
}

pub struct StartCastingEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StartCastingEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_entity_id(&mut self, entity_id: u64) {
    self.fbb_.push_slot::<u64>(StartCastingEvent::VT_ENTITY_ID, entity_id, 0);
  }
  #[inline]
  pub fn add_spell_id(&mut self, spell_id: u32) {
    self.fbb_.push_slot::<u32>(StartCastingEvent::VT_SPELL_ID, spell_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> StartCastingEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StartCastingEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<StartCastingEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for StartCastingEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("StartCastingEvent");
      ds.field("entity_id", &self.entity_id());
      ds.field("spell_id", &self.spell_id());
      ds.finish()
  }
}
