// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum VitalsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Vitals<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Vitals<'a> {
  type Inner = Vitals<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Vitals<'a> {
  pub const VT_HP: flatbuffers::VOffsetT = 4;
  pub const VT_MAX_HP: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Vitals { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VitalsArgs
  ) -> flatbuffers::WIPOffset<Vitals<'bldr>> {
    let mut builder = VitalsBuilder::new(_fbb);
    builder.add_max_hp(args.max_hp);
    builder.add_hp(args.hp);
    builder.finish()
  }


  #[inline]
  pub fn hp(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Vitals::VT_HP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max_hp(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Vitals::VT_MAX_HP, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Vitals<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("hp", Self::VT_HP, false)?
     .visit_field::<i32>("max_hp", Self::VT_MAX_HP, false)?
     .finish();
    Ok(())
  }
}
pub struct VitalsArgs {
    pub hp: i32,
    pub max_hp: i32,
}
impl<'a> Default for VitalsArgs {
  #[inline]
  fn default() -> Self {
    VitalsArgs {
      hp: 0,
      max_hp: 0,
    }
  }
}

pub struct VitalsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> VitalsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_hp(&mut self, hp: i32) {
    self.fbb_.push_slot::<i32>(Vitals::VT_HP, hp, 0);
  }
  #[inline]
  pub fn add_max_hp(&mut self, max_hp: i32) {
    self.fbb_.push_slot::<i32>(Vitals::VT_MAX_HP, max_hp, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> VitalsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VitalsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Vitals<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Vitals<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Vitals");
      ds.field("hp", &self.hp());
      ds.field("max_hp", &self.max_hp());
      ds.finish()
  }
}
