[package]
name = "web-client"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
schemas = { path = "../schemas" }
tokio = { workspace = true }
tracing = { workspace = true }
