[package]
name = "mmo-client"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
flatbuffers = "25.2.10"
schemas = { path = "../schemas" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
