name: MMO server push

on:
  push:
    paths:
      - ".github/workflows/mmo-server-push.yml"
      - "mmo-server"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.8.6
  SQLX_FEATURES: "rustls,postgres"

permissions:
      id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rejdeboer
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push mmo-server
        uses: docker/build-push-action@v6
        with:
          push: true
          target: mmo-server
          tags: rejdeboer/mmo-server:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PAT }}

  # modify-manifest:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out config repo
  #       uses: actions/checkout@v3
  #       with:
  #         repository: 'rejdeboer/multiplayer-deployment'
  #         token: ${{ secrets.PAT }}
  #
  #     - name: Modify application image
  #       run: |
  #         git config user.email rick.deboer@live.nl
  #         git config user.name rejdeboer
  #         sed -i "s+rejdeboer.azurecr.io/multiplayer-websocket:.*+rejdeboer.azurecr.io/multiplayer-websocket:${{ github.sha }}+g" deploy/multiplayer-websocket-deployment.yml
  #         git add .
  #         git commit -m 'automated: update multiplayer-websocket image'
  #         git push origin master
